name: Aufgerufener Workflow (Testausgabe)

on:
  workflow_call:
    inputs:
      deploy_path:
        description: 'Pfad auf dem Server'
        required: true
        type: string
      platform:
        description: 'Platform'
        required: true
        type: string

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "deploy_path=${{ inputs.deploy_path }}"
          echo "platform=${{ inputs.platform }}"
